const palette = {
  forest: "#1B4332",
  forestLight: "#2D6A4F",
  sage: "#52B788",
  mint: "#95D5B2",
  sand: "#F5E6CC",
  sandDark: "#D4A574",
  cream: "#FAF3E0",
  white: "#FFFFFF",
  black: "#0A0A0A",
  gray100: "#F7F7F7",
  gray200: "#E8E8E8",
  gray300: "#D1D1D1",
  gray500: "#8E8E93",
  gray700: "#48484A",
  gray900: "#1C1C1E",
  error: "#FF3B30",
  success: "#34C759",
  darkBg: "#0D1B12",
  darkSurface: "#162419",
  darkSurfaceSecondary: "#1E2E23",
  darkBorder: "#2A3D30",
};

export type ThemeColors = typeof Colors.light;

const Colors = {
  light: {
    text: palette.black,
    textSecondary: palette.gray500,
    background: palette.cream,
    surface: palette.white,
    surfaceSecondary: palette.gray100,
    tint: palette.forest,
    tintLight: palette.forestLight,
    accent: palette.sage,
    accentLight: palette.mint,
    sand: palette.sand,
    sandDark: palette.sandDark,
    border: palette.gray200,
    tabIconDefault: palette.gray500,
    tabIconSelected: palette.forest,
    error: palette.error,
    success: palette.success,
    forest: palette.forest,
    white: palette.white,
    mint: palette.mint,
    userBubble: palette.forest,
    userBubbleText: palette.white,
    assistantBubble: palette.white,
    assistantBubbleText: palette.black,
    inputBackground: palette.white,
    placeholder: palette.gray300,
  },
  dark: {
    text: palette.white,
    textSecondary: palette.gray500,
    background: palette.darkBg,
    surface: palette.darkSurface,
    surfaceSecondary: palette.darkSurfaceSecondary,
    tint: palette.sage,
    tintLight: palette.forestLight,
    accent: palette.sage,
    accentLight: palette.mint,
    sand: palette.sandDark,
    sandDark: palette.sand,
    border: palette.darkBorder,
    tabIconDefault: palette.gray500,
    tabIconSelected: palette.sage,
    error: palette.error,
    success: palette.success,
    forest: palette.forest,
    white: palette.white,
    mint: palette.mint,
    userBubble: palette.forestLight,
    userBubbleText: palette.white,
    assistantBubble: palette.darkSurfaceSecondary,
    assistantBubbleText: palette.white,
    inputBackground: palette.darkSurface,
    placeholder: palette.gray700,
  },
};

export default Colors;
